name = "SimplePlotly"
uuid = "aba6ae9e-30f2-43a5-bf1a-2a3639332844"
authors = ["Trevor Loe <tgloe@math.ucla.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
