name = "SimplePlotly"
uuid = "aba6ae9e-30f2-43a5-bf1a-2a3639332844"
authors = ["Trevor Loe <tgloe@math.ucla.edu>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"

[compat]
LinearAlgebra = "1.11.0"
PlotlyJS = "0.18.15"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
